### ISSUE TITLE
would be nice to have 1.20.2 support =)

### ISSUE THREAD

**Issue by CloudeLecaw** [PluginBugs/Issues-EpicBackpacks#103]
```
[08:54:07] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: ender
[08:54:07] [Server thread/ERROR]: Error occurred while enabling EpicBackpacks v1.3.16-r3 (Is it up to date?)
dev.lone.LoneLibs.nbt.nbtapi.NbtApiException: [?]Error while calling the method 'getTagType(java.lang.String)', loaded: true, Enum: COMPOUND_GET_TYPE, Passed Class: class java.lang.Boolean
	at dev.lone.LoneLibs.nbt.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:358) ~[?:?]
	at dev.lone.LoneLibs.nbt.nbtapi.NBTReflectionUtil.getData(NBTReflectionUtil.java:635) ~[?:?]
	at dev.lone.LoneLibs.nbt.nbtapi.NBTCompound.getType(NBTCompound.java:1016) ~[?:?]
	at dev.lone.LoneLibs.nbt.nbtapi.NBTCompound.addCompound(NBTCompound.java:669) ~[?:?]
	at dev.lone.LoneLibs.nbt.nbtapi.NBTCompound.getOrCreateCompound(NBTCompound.java:709) ~[?:?]
	at de.erethon.headlib.Generic.createOwnerCompound(Generic.java:64) ~[?:?]
	at de.erethon.headlib.HeadLib.setSkullOwner(HeadLib.java:411) ~[?:?]
	at de.erethon.headlib.HeadLib.setSkullOwner(HeadLib.java:407) ~[?:?]
	at dev.lone.EpicBackpacks.a.a(SourceFile:239) ~[?:?]
	at dev.lone.EpicBackpacks.i.c(SourceFile:185) ~[?:?]
	at dev.lone.EpicBackpacks.Main.c(SourceFile:172) ~[?:?]
	at dev.lone.EpicBackpacks.Main.f(SourceFile:160) ~[?:?]
	at dev.lone.EpicBackpacks.Main.onEnable(SourceFile:114) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:548) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3881-Spigot-17ca32d-f71a799]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:462) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3881-Spigot-17ca32d-f71a799]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:577) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3881-Spigot-17ca32d-f71a799]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:400) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3881-Spigot-17ca32d-f71a799]
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3881-Spigot-17ca32d-f71a799]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:954) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3881-Spigot-17ca32d-f71a799]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:298) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3881-Spigot-17ca32d-f71a799]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
Caused by: java.lang.IllegalArgumentException: object is not an instance of declaring class
	at jdk.internal.reflect.DirectMethodHandleAccessor.checkReceiver(DirectMethodHandleAccessor.java:202) ~[?:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:100) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at dev.lone.LoneLibs.nbt.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:355) ~[?:?]
	... 23 more
```
i aspect an update of lonedev libs is needed too

**Comment by CloudeLecaw** [comment]
Well currently we cant use R4 because of this
https://github.com/PluginBugs/Issues-EpicBackpacks/issues/101

i hope for a fix. maybe with official 1.20.2 support and a fix for the issue from ticket 101 =)

**Comment by LoneDev6** [comment]
This is a bug of LoneLibs, will be fixed in the upcoming LoneLibs update which will be released today.
https://www.spigotmc.org/resources/lonelibs.75974
Thanks!
