### ISSUE TITLE
Would be nice to have Server 1.21.1 Support

### ISSUE THREAD

**Issue by CloudeLecaw** [PluginBugs/Issues-EpicBackpacks#119]
Spigot and the first paper builds are out

Currently the plugin does not load on 1.21.1  mights its just the LoneDevLibs that needs an update?

```
[19:37:07] [Server thread/INFO]: [EpicBackpacks] Enabling EpicBackpacks v1.3.17-release-2
[19:37:07] [Server thread/INFO]: [m
[19:37:07] [Server thread/INFO]: [0;33;1m-[0;33;22m=[0;30;1m[[0;32;1m[21m EpicBackPacks [0;30;1m][0;33;22m=[0;33;1m-[m
[19:37:07] [Server thread/INFO]: [m
[19:37:07] [Server thread/INFO]: [0;33;22mVersion: [0;36;1m1.3.17-release-2[m
[19:37:07] [Server thread/INFO]: [0;33;22mServer version: [0;36;1mv1_21_R1[m
[19:37:07] [Server thread/INFO]: [m
[19:37:07] [Server thread/INFO]: [m
[19:37:07] [Server thread/INFO]: [EpicBackpacks] Loading backpack: ender
[19:37:07] [Server thread/INFO]: [EpicBackpacks] Loading backpack: brown
[19:37:07] [Server thread/INFO]: [EpicBackpacks] Loading backpack: red
[19:37:07] [Server thread/INFO]: [EpicBackpacks] Loading backpack: yellow
[19:37:07] [Server thread/INFO]: [EpicBackpacks] Loading backpack: purple
[19:37:07] [Server thread/INFO]: [EpicBackpacks] Loading backpack: pink
[19:37:07] [Server thread/INFO]: [EpicBackpacks] Loading backpack: orange
[19:37:07] [Server thread/INFO]: [EpicBackpacks] Loading backpack: green
[19:37:07] [Server thread/INFO]: [EpicBackpacks] Loading backpack: blue
[19:37:07] [Server thread/INFO]: [EpicBackpacks] Loading backpack: strange
[19:37:07] [Server thread/INFO]: [EpicBackpacks] Loading backpack: chest
[19:37:07] [Server thread/INFO]: [EpicBackpacks] Loading backpack: wood
[19:37:07] [Server thread/INFO]: [EpicBackpacks] Loading backpack: stone
[19:37:07] [Server thread/INFO]: [EpicBackpacks] Loading backpack: redstone
[19:37:07] [Server thread/INFO]: [EpicBackpacks] Loading backpack: minerals
[19:37:07] [Server thread/INFO]: [EpicBackpacks] Loading backpack: magicblue
[19:37:07] [Server thread/INFO]: [EpicBackpacks] Loading recipe for backpack: ender
[19:37:08] [Server thread/WARN]: [NBTAPI] Unable to find the method 'UnmappedreadCompressed(java.io.InputStream,net.minecraft.nbt.NbtAccounter)' in 'NBTCompressedStreamTools' Args: [class java.io.InputStream, class net.minecraft.nbt.NBTReadLimiter] Enum: NBTFILE_READV2
[19:37:08] [Server thread/WARN]: [NBTAPI] Unable to find the method 'UnmappedunlimitedHeap()' in 'NBTReadLimiter' Args: [] Enum: NBTACCOUNTER_CREATE_UNLIMITED
[19:37:08] [Server thread/WARN]: [NBTAPI] Unable to find the method 'Unmappedget(net.minecraft.core.component.DataComponentType)' in 'DataComponentHolder' Args: [interface net.minecraft.core.component.DataComponentType] Enum: NMSDATACOMPONENTHOLDER_GET
[19:37:08] [Server thread/WARN]: [NBTAPI] Unable to find the method 'UnmappedcopyTag()' in 'CustomData' Args: [] Enum: NMSCUSTOMDATA_GETCOPY
[19:37:08] [Server thread/WARN]: [NBTAPI] Unable to find the method 'Unmappedset(net.minecraft.core.component.DataComponentType,java.lang.Object)' in 'ItemStack' Args: [interface net.minecraft.core.component.DataComponentType, class java.lang.Object] Enum: NMSITEM_SET
[19:37:08] [Server thread/WARN]: [NBTAPI] Unable to find the method 'Unmappedsave(net.minecraft.core.HolderLookup$Provider)' in 'ItemStack' Args: [interface net.minecraft.core.HolderLookup$a] Enum: NMSITEM_SAVE_MODERN
[19:37:08] [Server thread/WARN]: [NBTAPI] Unable to find the method 'UnmappedparseOptional(net.minecraft.core.HolderLookup$Provider,net.minecraft.nbt.CompoundTag)' in 'ItemStack' Args: [interface net.minecraft.core.HolderLookup$a, class net.minecraft.nbt.NBTTagCompound] Enum: NMSITEM_LOAD
[19:37:08] [Server thread/WARN]: [NBTAPI] Unable to find the method 'UnmappedregistryAccess()' in 'MinecraftServer' Args: [] Enum: NMSSERVER_GETREGISTRYACCESS
[19:37:08] [Server thread/WARN]: [NBTAPI] Unable to find the method 'UnmappedsaveWithId(net.minecraft.core.HolderLookup$Provider)' in 'TileEntity' Args: [interface net.minecraft.core.HolderLookup$a] Enum: TILEENTITY_GET_NBT_1205
[19:37:08] [Server thread/WARN]: [NBTAPI] Unable to find the method 'UnmappedloadWithComponents(net.minecraft.nbt.CompoundTag,net.minecraft.core.HolderLookup$Provider)' in 'TileEntity' Args: [class net.minecraft.nbt.NBTTagCompound, interface net.minecraft.core.HolderLookup$a] Enum: TILEENTITY_SET_NBT_1205
[19:37:08] [Server thread/WARN]: [NBTAPI] Unable to find the method 'UnmappedgetDataFixer()' in 'DataConverterRegistry' Args: [] Enum: GET_DATAFIXER
[19:37:08] [Server thread/ERROR]: Error occurred while enabling EpicBackpacks v1.3.17-release-2 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at dev.lone.LoneLibs.nbt.nbtapi.NBTCompound.getType(NBTCompound.java:1348) ~[?:?]
	at dev.lone.LoneLibs.nbt.nbtapi.NBTCompound.addCompound(NBTCompound.java:765) ~[?:?]
	at dev.lone.LoneLibs.nbt.nbtapi.NBTCompound.getOrCreateCompound(NBTCompound.java:805) ~[?:?]
	at de.erethon.headlib.Generic.createOwnerCompound(Generic.java:64) ~[?:?]
	at de.erethon.headlib.HeadLib.setSkullOwner(HeadLib.java:411) ~[?:?]
	at de.erethon.headlib.HeadLib.setSkullOwner(HeadLib.java:407) ~[?:?]
	at dev.lone.EpicBackpacks.a.a(SourceFile:247) ~[?:?]
	at dev.lone.EpicBackpacks.h.d(SourceFile:202) ~[?:?]
	at dev.lone.EpicBackpacks.Main.d(SourceFile:178) ~[?:?]
	at dev.lone.EpicBackpacks.Main.g(SourceFile:166) ~[?:?]
	at dev.lone.EpicBackpacks.Main.onEnable(SourceFile:117) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:492) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugin(CraftServer.java:567) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4223-Spigot-146439e-d01c70e]
	at org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugins(CraftServer.java:481) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4223-Spigot-146439e-d01c70e]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4223-Spigot-146439e-d01c70e]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:426) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4223-Spigot-146439e-d01c70e]
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:269) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4223-Spigot-146439e-d01c70e]
	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1017) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4223-Spigot-146439e-d01c70e]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4223-Spigot-146439e-d01c70e]
	at java.base/java.lang.Thread.run(Thread.java:1570) [?:?]
Caused by: java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:220) ~[?:?]
	at java.base/java.lang.Class.getDeclaredField(Class.java:2784) ~[?:?]
	at dev.lone.LoneLibs.nbt.nbtapi.NBTReflectionUtil.<clinit>(NBTReflectionUtil.java:59) ~[?:?]
	... 22 more
```

**Comment by CloudeLecaw** [comment]
well 3 weeks has passt. i know your busy. but would still be nice to see Epicbackpacks on Spigot 1.21 its one of the last two plugins we wanne see back :3

**Comment by LoneDev6** [comment]
EpicBackpacks is receiving a complete recode, so it requires some time.
The old version won't be updated anymore due to its limitations and difficulty to extend.

**Comment by CloudeLecaw** [comment]
Any news about that? :3 the 1.21.1 was relaased allready a while ago :3

**Comment by CCjun6** [comment]
> EpicBackpacks 正在进行全面重新编码，因此需要一些时间。 旧版本由于其局限性和扩展难度，将不再更新。
I don't like to rush people, but it's been three months since the issue was raised.

**Comment by CCjun6** [comment]
> EpicBackpacks is receiving a complete recode, so it requires some time. The old version won't be updated anymore due to its limitations and difficulty to extend.

I don't like to rush people, but it's been three months since the issue was raised.

**Comment by CloudeLecaw** [comment]
and i asume it will be some months more
.. 8-)

**Comment by SinistersGrin** [comment]
its been basically 8 months, we love and appreciate your time and work and its understandable a complete recode takes time, is there an ETA please... just for some of us to know when we will be able to update our servers.

**Comment by CloudeLecaw** [comment]
personaly we decided to not use these plugins anmyore. we made a little 1.20.4 server we we used the plugins on and take off all bank accounts (RPG-Banker) stuff from the players and their backpacks (EpicBackpacks) and transported the "new" playerdata with the items to the new server.

Then we placed the items in chests in their houses. and refound the players their stored money on their back accounts on the live server.
Took long time because we has xxx banker accounts. lucky just a few had  backpaks.

Even if there will be a recode / remake. We cant wait 8 months and longer just to gave players acesss aggain to their stuff.
Time is going on and player can be very very jostle for their staff. xD
