### ISSUE TITLE
Little Update for 1.17 might be needed

### ISSUE THREAD

**Issue by CloudeLecaw** [PluginBugs/Issues-EpicBackpacks#26]
PaperMC 1.17
Protocollib  Build 520 (for 1.17)
LoneDevLib 1.0.11

Issue
 accour  on startup of the Server
```
[14:52:20] [Server thread/INFO]: [EpicBackpacks] Enabling EpicBackpacks v1.3.2
[14:52:20] [Votifier NIO boss/INFO]: [Votifier] Votifier enabled on socket /[0:0:0:0:0:0:0:0]:8192.
[14:52:21] [Server thread/INFO]: 
[14:52:21] [Server thread/INFO]: -=[ EpicBackPacks ]=-
[14:52:21] [Server thread/INFO]: 
[14:52:21] [Server thread/INFO]: Version: 1.3.2
[14:52:21] [Server thread/INFO]: Server version: v1_17_R1
[14:52:21] [Server thread/INFO]: 
[14:52:21] [Server thread/INFO]: 
[14:52:21] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: example_1
[14:52:21] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: example_2
[14:52:21] [Server thread/INFO]: [EpicBackpacks] Loaded backpack: ender
[14:52:21] [Server thread/ERROR]: HeadLib could not find a valid implementation for v1_17_R1.
[14:52:21] [Server thread/ERROR]: Error occurred while enabling EpicBackpacks v1.3.2 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "de.erethon.headlib.HeadLib$InternalsProvider.createOwnerCompound(String, String)" because "de.erethon.headlib.HeadLib.internals" is null
	at de.erethon.headlib.HeadLib.setSkullOwner(HeadLib.java:522) ~[?:?]
	at de.erethon.headlib.HeadLib.setSkullOwner(HeadLib.java:508) ~[?:?]
	at dev.lone.EpicBackpacks.a.a(Unknown Source) ~[?:?]
	at dev.lone.EpicBackpacks.h.f(Unknown Source) ~[?:?]
	at dev.lone.EpicBackpacks.Main.f(Unknown Source) ~[?:?]
	at dev.lone.EpicBackpacks.Main.i(Unknown Source) ~[?:?]
	at dev.lone.EpicBackpacks.Main.onEnable(Unknown Source) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.jar:git-Paper-"1830de5"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.jar:git-Paper-"1830de5"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.jar:git-Paper-"1830de5"]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.17.jar:git-Paper-"1830de5"]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.17.jar:git-Paper-"1830de5"]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:643) ~[patched_1.17.jar:git-Paper-"1830de5"]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:303) ~[patched_1.17.jar:git-Paper-"1830de5"]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1118) ~[patched_1.17.jar:git-Paper-"1830de5"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-"1830de5"]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[14:52:21] [Server thread/INFO]: [EpicBackpacks] Disabling EpicBackpacks v1.3.2
```

**Comment by CloudeLecaw** [comment]
Solved with latest update <3
