### ISSUE TITLE
Error when closing inventories

### ISSUE THREAD

**Issue by CloudeLecaw** [PluginBugs/Issues-EpicBackpacks#64]
PaperMC 1.18.2
EpicBackPacks_1.3.14
Libs 1.0.18

Issue happen when  someone loggs out

```
[22:50:38] [Server thread/ERROR]: [31m[Minecraft] Could not pass event InventoryCloseEvent to EpicBackpacks v1.3.14[0m
java.lang.NullPointerException: Cannot invoke "dev.lone.EpicBackpacks.k.d()" because "<local2>" is null
	at dev.lone.EpicBackpacks.d.a(SourceFile:308) ~[EpicBackPacks_1.3.14.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-283]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1532) ~[paper-1.18.2.jar:git-Paper-283]
	at net.minecraft.server.level.ServerPlayer.closeContainer(ServerPlayer.java:1575) ~[?:?]
	at org.bukkit.craftbukkit.v1_18_R2.entity.CraftHumanEntity.closeInventory(CraftHumanEntity.java:539) ~[paper-1.18.2.jar:git-Paper-283]
	at net.minecraft.server.level.ServerLevel$EntityCallbacks.onTrackingEnd(ServerLevel.java:2518) ~[?:?]
	at net.minecraft.server.level.ServerLevel$EntityCallbacks.a(ServerLevel.java:2410) ~[?:?]
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.stopTracking(PersistentEntitySectionManager.java:232) ~[paper-1.18.2.jar:git-Paper-283]
	at net.minecraft.world.level.entity.PersistentEntitySectionManager$Callback.onRemove(PersistentEntitySectionManager.java:614) ~[?:?]
	at net.minecraft.world.entity.Entity.setRemoved(Entity.java:4244) ~[paper-1.18.2.jar:git-Paper-283]
	at net.minecraft.world.entity.Entity.remove(Entity.java:617) ~[paper-1.18.2.jar:git-Paper-283]
	at net.minecraft.world.entity.player.Player.remove(Player.java:1455) ~[?:?]
	at net.minecraft.server.level.ServerLevel.removePlayerImmediately(ServerLevel.java:1469) ~[?:?]
	at net.minecraft.server.players.PlayerList.remove(PlayerList.java:663) ~[paper-1.18.2.jar:git-Paper-283]
	at net.minecraft.server.players.PlayerList.remove(PlayerList.java:602) ~[paper-1.18.2.jar:git-Paper-283]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2009) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:1989) ~[?:?]
	at net.minecraft.network.Connection.handleDisconnection(Connection.java:755) ~[?:?]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:221) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1620) ~[paper-1.18.2.jar:git-Paper-283]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-283]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1455) ~[paper-1.18.2.jar:git-Paper-283]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[paper-1.18.2.jar:git-Paper-283]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-283]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by CloudeLecaw** [comment]
No the did not even have one

**Comment by nivcoo** [comment]
Yes i've the same issue https://pics.revolis.fr/2022/04/14/18-44_iaUR.png

**Comment by nivcoo** [comment]
And i think this bug can create losses

**Comment by CloudeLecaw** [comment]
We downgraded on our 1.18.2 Server to EpicBackPacks_1.3.13
