### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Matzethelexx** [PluginBugs/Issues-EpicBackpacks#65]
PaperMC 1.18.2
EpicBackPacks_1.3.14
Libs 1.0.18

The backpacks are only in the inventory and not opened.
The content is retained. this error message comes up every time. when I change servers

Thank you.

ERROR
19:10:32

Could not pass event InventoryCloseEvent to EpicBackpacks v1.3.14

Console
19:10:32

java.lang.NullPointerException: Cannot invoke "dev.lone.EpicBackpacks.k.d()" because "<local2>" is null
at dev.lone.EpicBackpacks.d.a(SourceFile:308) ~[EpicBackPacks_1.3.14.jar:?]
at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-274]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1532) ~[paper-1.18.2.jar:git-Paper-274]
at net.minecraft.server.level.ServerPlayer.closeContainer(ServerPlayer.java:1575) ~[?:?]
at org.bukkit.craftbukkit.v1_18_R2.entity.CraftHumanEntity.closeInventory(CraftHumanEntity.java:539) ~[paper-1.18.2.jar:git-Paper-274]
at net.minecraft.server.level.ServerLevel$EntityCallbacks.onTrackingEnd(ServerLevel.java:2512) ~[?:?]
at net.minecraft.server.level.ServerLevel$EntityCallbacks.a(ServerLevel.java:2410) ~[?:?]
at com.bergerkiller.bukkit.common.internal.logic.EntityAddRemoveHandler_1_17$Hook.a(Unknown Source) ~[?:?]
at net.minecraft.world.level.entity.PersistentEntitySectionManager.stopTracking(PersistentEntitySectionManager.java:232) ~[paper-1.18.2.jar:git-Paper-274]
at net.minecraft.world.level.entity.PersistentEntitySectionManager$Callback.onRemove(PersistentEntitySectionManager.java:614) ~[?:?]
at net.minecraft.world.entity.Entity.setRemoved(Entity.java:4244) ~[paper-1.18.2.jar:git-Paper-274]
at net.minecraft.world.entity.Entity.remove(Entity.java:617) ~[paper-1.18.2.jar:git-Paper-274]
at net.minecraft.world.entity.player.Player.remove(Player.java:1455) ~[?:?]
at net.minecraft.server.level.ServerLevel.removePlayerImmediately(ServerLevel.java:1469) ~[?:?]
at net.minecraft.server.players.PlayerList.remove(PlayerList.java:663) ~[paper-1.18.2.jar:git-Paper-274]
at net.minecraft.server.players.PlayerList.remove(PlayerList.java:602) ~[paper-1.18.2.jar:git-Paper-274]
at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2009) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:1989) ~[?:?]
at net.minecraft.network.Connection.handleDisconnection(Connection.java:755) ~[?:?]
at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:221) ~[?:?]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1620) ~[paper-1.18.2.jar:git-Paper-274]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-274]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1455) ~[paper-1.18.2.jar:git-Paper-274]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[paper-1.18.2.jar:git-Paper-274]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-274]
at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by CloudeLecaw** [comment]
Same as here reported
https://github.com/PluginBugs/Issues-EpicBackpacks/issues/64

For now i recommend you to downgrade to 1.3.13
