### ISSUE TITLE
[BUG] Another duplication issue

### ISSUE THREAD

**Issue by Sixsoul** [PluginBugs/Issues-EpicBackpacks#71]
**Describe the bug**
Ahhh, sorry back again with another one. I've had multiple player reports now of backpacks duplicating the contents of other backpacks. Example: I have one backpack with 64 Netherite Blocks in it and another backpack with 1 Dirt Block in it. I open the dirt backpack and suddenly instead of showing the dirt that it should have, it has the Netherite Blocks in it for some reason. You can remove the blocks from both backpacks individually and boom, now you've duped your netherite blocks.

**To Reproduce**
1. I am unable to recreate this issue myself, but I've now had 3 separate players report it happening all at different times. According to their reports there is no clear method to replicate the problem, it just happens randomly. I thought it was a fluke but it seems to be a recurring issue now.

If it's worth anything, I use SQL for storage.

**Expected behavior**
Backpacks should maintain their own inventories instead of duping others.

**Info (please complete the following information):**
 - Server version:Paper 1.18.2
 - Client version: Any
 - Plugin version: 1.3.16

**Comment by LoneDev6** [comment]
This is quite strange.
Anyway mysql is not the issue since it doesn't sync physical backpacks, only the virtual ones opened with /ebp.

I really need your players to find out exactly how to trigger this behaviour or I cannot elaborate a fix.
The plugin was heavily tested and no duplication happened, maybe it has to do with another plugin (which I have to add support obviously).

**Comment by Sixsoul** [comment]
I mean...there is no way to recreate it reliably. It's just a random occurrence. All the player does on their end is have more than one backpack and then open one and boom, it dupes the other one sometimes.

**Comment by LoneDev6** [comment]
I'll do some tests to see if I can manage to do that

**Comment by adamboof** [comment]
This is reliable re-creatable with the following steps;
1. Have 2 backpacks
2. Put items into one backpack
3. Go to an NPC with a GUI
4. Have backpack with items in hand
5. Right-click on NPC to open GUI and backpack will open
6. Change to other backpack
7. Keep right-clicking with new backpack
8. Items from other backpack displays
9. Profit

**Comment by adamboof** [comment]
Seems like this error gets posted to the console
`java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.Inventory.getContents()" because "<local4>" is null
	at dev.lone.EpicBackpacks.d.a(SourceFile:86) ~[EpicBackpacks_1.3.16-r1.jar:?]
	at dev.lone.EpicBackpacks.d.a(SourceFile:326) ~[EpicBackpacks_1.3.16-r1.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-196]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1523) ~[paper-1.19.2.jar:git-Paper-196]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClose(ServerGamePacketListenerImpl.java:3069) ~[?:?]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:1337) ~[paper-1.19.2.jar:git-Paper-196]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:1332) ~[paper-1.19.2.jar:git-Paper-196]
	at org.bukkit.craftbukkit.v1_19_R1.entity.CraftHumanEntity.openCustomInventory(CraftHumanEntity.java:354) ~[paper-1.19.2.jar:git-Paper-196]
	at org.bukkit.craftbukkit.v1_19_R1.entity.CraftHumanEntity.openInventory(CraftHumanEntity.java:339) ~[paper-1.19.2.jar:git-Paper-196]
	at dev.lone.EpicBackpacks.d.a(SourceFile:162) ~[EpicBackpacks_1.3.16-r1.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-196]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.2.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.2.jar:git-Paper-196]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.2.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-196]
`
