### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Wgis** [PluginBugs/Issues-EpicBackpacks#79]
**Describe the bug**
After some time i got this problem. Looks what all good, tables are created. But this error...

**To Reproduce**
-

**Expected behavior**
-

**Screenshots**
-

**Info (please complete the following information):**
 - Server version: paper 1.19.2
 - Client version: fabric 1.19.2
 - Plugin version: EpicBackpacks_1.3.16-r1.jar

**Additional context**
DB Config:
`mysql:
  enabled: true
  host: mysql.joinserver.xyz
  port: 3306
  flags: ?autoReconnect=true
  username: user
  password: pass
  database: db_name
  table: epic_backpacks
  load-save-messages-in-console: true`
Error:
```
[11:04:11 WARN]: com.mysql.cj.jdbc.exceptions.CommunicationsException: The last packet successfully received from the server was 1,138,906 milliseconds ago. The last packet sent successfully to the server was 1,138,907 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
[11:04:11 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
[11:04:11 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
[11:04:11 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
[11:04:11 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:972)
[11:04:11 WARN]:        at EpicBackpacks_1.3.16-r1.jar//dev.lone.EpicBackpacks.main.F.run(SourceFile:60)
[11:04:11 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[11:04:11 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[11:04:11 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[11:04:11 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[11:04:11 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[11:04:11 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[11:04:11 WARN]: Caused by: com.mysql.cj.exceptions.CJCommunicationsException: The last packet successfully received from the server was 1,138,906 milliseconds ago. The last packet sent successfully to the server was 1,138,907 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
[11:04:11 WARN]:        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
[11:04:11 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[11:04:11 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:483)
[11:04:11 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
[11:04:11 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
[11:04:11 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
[11:04:11 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
[11:04:11 WARN]:        at com.mysql.cj.protocol.a.NativeProtocol.send(NativeProtocol.java:628)
[11:04:11 WARN]:        at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:683)
[11:04:11 WARN]:        at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:1051)
[11:04:11 WARN]:        at com.mysql.cj.NativeSession.execSQL(NativeSession.java:665)
[11:04:11 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:893)
[11:04:11 WARN]:        ... 8 more
[11:04:11 WARN]: Caused by: java.net.SocketException: Connection reset by peer
[11:04:11 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.implWrite(NioSocketImpl.java:417)
[11:04:11 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.write(NioSocketImpl.java:437)
[11:04:11 WARN]:        at java.base/sun.nio.ch.NioSocketImpl$2.write(NioSocketImpl.java:823)
[11:04:11 WARN]:        at java.base/java.net.Socket$SocketOutputStream.write(Socket.java:1035)
[11:04:11 WARN]:        at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
[11:04:11 WARN]:        at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
[11:04:11 WARN]:        at com.mysql.cj.protocol.a.SimplePacketSender.send(SimplePacketSender.java:55)
[11:04:11 WARN]:        at com.mysql.cj.protocol.a.TimeTrackingPacketSender.send(TimeTrackingPacketSender.java:50)
[11:04:11 WARN]:        at com.mysql.cj.protocol.a.NativeProtocol.send(NativeProtocol.java:619)
[11:04:11 WARN]:        ... 12 more
[11:04:11 ERROR]: [EpicBackpacks] [!] Error loading backpack from MySql (saving the file to current server). Player: Wgis
[11:04:11 WARN]: org.bukkit.configuration.InvalidConfigurationException: Top level is not a Map.
[11:04:11 WARN]:        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:107)
[11:04:11 WARN]:        at EpicBackpacks_1.3.16-r1.jar//dev.lone.EpicBackpacks.e.b(SourceFile:100)
[11:04:11 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
[11:04:11 WARN]:        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
[11:04:11 WARN]:        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
[11:04:11 WARN]:        at EpicBackpacks_1.3.16-r1.jar//dev.lone.EpicBackpacks.main.F.run(SourceFile:67)
[11:04:11 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[11:04:11 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[11:04:11 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[11:04:11 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[11:04:11 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[11:04:11 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by LoneDev6** [comment]
Write in english, I don't speak russian

**Comment by Wgis** [comment]
I have problems with connection to database. After some time i get this warn. But tables for plugin created and have some data.

**Comment by LoneDev6** [comment]
It is probably a connection issue, the database code was tested and working correctly.
The error states that the connection is very slow.
