### ISSUE TITLE
[BUG] error in 1.19.3

### ISSUE THREAD

**Issue by Dalethium** [PluginBugs/Issues-EpicBackpacks#81]
```
[17:06:52 WARN]: [EpicBackpacks] Plugin EpicBackpacks v1.3.16-r1 generated an exception while executing task 1501369

java.lang.ClassCastException: class net.minecraft.nbt.NBTTagCompound cannot be cast to class java.util.Set (net.minecraft.nbt.NBTTagCompound is in unnamed module of loader java.net.URLClassLoader @ba8a1dc; java.util.Set is in module java.base of loader 'bootstrap')

	at dev.lone.LoneLibs.nbt.nbtapi.NBTReflectionUtil.getKeys(NBTReflectionUtil.java:588) ~[LoneLibs.jar:?]

	at dev.lone.LoneLibs.nbt.nbtapi.NBTCompound.getKeys(NBTCompound.java:542) ~[LoneLibs.jar:?]

	at dev.lone.EpicBackpacks.a.a(SourceFile:426) ~[EpicBackpacks_1.3.16-r1.jar:?]

	at dev.lone.EpicBackpacks.a.a(SourceFile:368) ~[EpicBackpacks_1.3.16-r1.jar:?]

	at dev.lone.EpicBackpacks.d.a(SourceFile:140) ~[EpicBackpacks_1.3.16-r1.jar:?]

	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.3.jar:git-Paper-353]

	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.3.jar:git-Paper-353]

	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.3.jar:?]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]

	at java.lang.Thread.run(Thread.java:833) ~[?:?]

```

This server is running Paper version git-Paper-353 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 8e83c3c)
LoneLibs: 1.0.22
IA: 3.3.0b-r2
EBP: 1.3.16-r1
in game chat says "Backpack is loading…." and this error pops in console, seems to be breaking all backpacks. Was not present in 1.19.2 but I can't give you an exact timeline on when this started other than it was definitely at least for the 1.19.3 update.

Let me know what else is needed to fix this, thanks!

**Comment by LoneDev6** [comment]
1.19.3 is not supported, I'll release an update this week, thanks
