### ISSUE TITLE
[BUG] When trying to open a backpack with the default config, I get an error in console and the backpack doesn't open.

### ISSUE THREAD

**Issue by imparium-de** [PluginBugs/Issues-EpicBackpacks#82]
**Describe the bug**
When trying to open a backpack with the default config, I get an error in console and the backpack doesn't open.

**To Reproduce**
1. Use /ebpget brown
2. Error in console

**Expected behavior**
The backpack should open

**Info (please complete the following information):**
 - Server version: Paper 1.19.3
 - Client version: Fabric 1.19.3
 - Plugin version: 1.3.16-r2

**Additional context**
Console output:

[18:23:08 INFO]: [EpicBackpacks] Enabling EpicBackpacks v1.3.16-r2
[18:23:09 INFO]: 
[18:23:09 INFO]: -=[ EpicBackPacks ]=-
[18:23:09 INFO]: 
[18:23:09 INFO]: Version: 1.3.16-r2
[18:23:09 INFO]: Server version: v1_19_R2
[18:23:09 INFO]: 
[18:23:09 INFO]: 
[18:23:09 INFO]: [EpicBackpacks] [STDOUT] [MySQL] Connected to jdbc:mysql://178.xx.xx.xx:3306/epicbackpacks
[18:23:09 INFO]: [EpicBackpacks] Loading derMiepz personal backpack from MySQL db
[18:23:09 INFO]: [EpicBackpacks] Loaded backpack: example_1
[18:23:09 INFO]: [EpicBackpacks] Loaded backpack: example_2
[18:23:09 INFO]: [EpicBackpacks] Loaded backpack: example_3
[18:23:09 INFO]: [EpicBackpacks] Loaded backpack: ender
[18:23:09 INFO]: [EpicBackpacks] Loaded backpack: brown
[18:23:09 INFO]: [EpicBackpacks] Loaded backpack: red
[18:23:09 INFO]: [EpicBackpacks] Loaded backpack: yellow
[18:23:09 INFO]: [EpicBackpacks] Loaded backpack: purple
[18:23:09 INFO]: [EpicBackpacks] Loaded backpack: pink
[18:23:09 INFO]: [EpicBackpacks] Loaded backpack: orange
[18:23:09 INFO]: [EpicBackpacks] Loaded backpack: green
[18:23:09 INFO]: [EpicBackpacks] Loaded backpack: blue
[18:23:09 INFO]: [EpicBackpacks] Loaded backpack: strange
[18:23:09 INFO]: [EpicBackpacks] Loaded backpack: chest
[18:23:09 INFO]: [EpicBackpacks] Loaded backpack: wood
[18:23:09 INFO]: [EpicBackpacks] Loaded backpack: stone
[18:23:09 INFO]: [EpicBackpacks] Loaded backpack: redstone
[18:23:09 INFO]: [EpicBackpacks] Loaded backpack: minerals
[18:23:09 INFO]: [EpicBackpacks] §aLoaded backpacks correctly
[18:23:09 INFO]: [STDOUT] [dev.lone.EpicBackpacks.util.f] load.loadedEpicBackpacks
[18:23:09 INFO]: [EpicBackpacks] [OK] Loaded derMiepz personal backpack from MySQL db
[18:23:27 INFO]: derMiepz issued server command: /ebpget brown
[18:23:29 WARN]: [EpicBackpacks] Plugin EpicBackpacks v1.3.16-r2 generated an exception while executing task 20487
java.lang.ClassCastException: class net.minecraft.nbt.NBTTagCompound cannot be cast to class java.util.Set (net.minecraft.nbt.NBTTagCompound is in unnamed module of loader java.net.URLClassLoader @421faab1; java.util.Set is in module java.base of loader 'bootstrap')
        at dev.lone.LoneLibs.nbt.nbtapi.NBTReflectionUtil.getKeys(NBTReflectionUtil.java:588) ~[LoneLibs.jar:?]
        at dev.lone.LoneLibs.nbt.nbtapi.NBTCompound.getKeys(NBTCompound.java:542) ~[LoneLibs.jar:?]
        at dev.lone.EpicBackpacks.a.a(SourceFile:431) ~[EpicBackpacks.jar:?]
        at dev.lone.EpicBackpacks.a.a(SourceFile:373) ~[EpicBackpacks.jar:?]
        at dev.lone.EpicBackpacks.e.a(SourceFile:140) ~[EpicBackpacks.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.3.jar:git-Paper-380]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.3.jar:git-Paper-380]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.3.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by LoneDev6** [comment]
Did you update LoneLibs?

**Comment by imparium-de** [comment]
I just updated LoneLibs and it seems to have fixed this issue. Thanks!
