### ISSUE TITLE
Internal error when using MANGROVE_LOG in the whitelist

### ISSUE THREAD

**Issue by alimix3** [PluginBugs/Issues-EpicBackpacks#88]
**Describe the bug**
When creating a backpack, using the MANGROVE_LOG or the STRIPPED_MANGROVE_LOG in the whitelist results in a null exception.

**To Reproduce**
1. Create any backpack
2. Setup the whitelist with the MANGROVE_LOG or the STRIPPED_MANGROVE_LOG item
3. Reload the plugin

**Expected behavior**
Since the plugin has 1.19 support, this item should be allowed in the whitelist

**Info (please complete the following information):**
 - Server version: 1.19.2
 - Client version: 1.19.3
 - Plugin version: 1.3.16-r3

**Additional context**
Backpack config

```yaml
  woodcutter-t1:
    enabled: true
    display_name: '&f'
    display_name_gui: "&f"
    can_auto_pickup: true
    show_in_menu: false
    item:
      type: ITEM
      material: FIREWORK_STAR
      custom_model_data: 5
    size: 1
    open_delay: 0
    whitelist:
    - MANGROVE_LOG
```

Error thrown
> .[07:54:49 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ebpreload' in plugin EpicBackpacks v1.3.16-r3
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:916) ~[paper-1.19.2.jar:git-Paper-235]
        at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.19.2.jar:git-Paper-235]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.19.2.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:305) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:289) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2294) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2248) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.2.jar:git-Paper-235]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.2.jar:git-Paper-235]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.2.jar:git-Paper-235]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.2.jar:git-Paper-235]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.2.jar:git-Paper-235]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.2.jar:git-Paper-235]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.2.jar:git-Paper-235]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-235]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: No enum constant dev.lone.LoneLibs.Mat.COCOA_SEEDS
        at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
        at dev.lone.LoneLibs.Mat.valueOf(Mat.java:31) ~[LoneLibs.jar:?]
        at dev.lone.EpicBackpacks.i.c(SourceFile:169) ~[EpicBackpacks_1.3.16-r3.jar:?]
        at dev.lone.EpicBackpacks.Main.c(SourceFile:172) ~[EpicBackpacks_1.3.16-r3.jar:?]
        at dev.lone.EpicBackpacks.Main.f(SourceFile:160) ~[EpicBackpacks_1.3.16-r3.jar:?]
        at dev.lone.EpicBackpacks.Main.e(SourceFile:140) ~[EpicBackpacks_1.3.16-r3.jar:?]
        at dev.lone.EpicBackpacks.main.l.a(SourceFile:22) ~[EpicBackpacks_1.3.16-r3.jar:?]
        at dev.lone.EpicBackpacks.main.l.onCommand(SourceFile:14) ~[EpicBackpacks_1.3.16-r3.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        ... 23 more

**Comment by LoneDev6** [comment]
Will be checked as soon as possible. Thanks for the patience.
